export const ACTION_TYPES = {
  SET_IS_LOADING: 'SET_IS_LOADING',
  SET_COMPANY: 'SET_COMPANY',
  SET_DIRECTORS: 'SET_DIRECTORS',
  SET_MANAGERS: 'SET_MANAGERS',
  SET_SELECTED_DIRECTOR: 'SET_SELECTED_DIRECTOR',
  SET_SELECTED_MANAGER: 'SET_SELECTED_MANAGER',
}